enum AppConstants {
    static let displayName = "Black Hole Codex Quota Indicator"
    static let hideInFullScreenAppsKey = "hideInFullScreenApps"
    static let showOnlyWhenCodexIsActiveKey = "showOnlyWhenCodexIsActive"
    static let responseNoticesKey = "responseNotices"
    static let responseNotifyFingerprintKey = "responseNotifyFingerprint"
    static let responseNotifyTokenKey = "responseNotifyToken"
    static let petSizeKey = "petSize"
    static let tooltipStyleKey = "tooltipStyle"
    static let showQuotaDynamicsKey = "showQuotaDynamics"
    static let showCodexResetForecastKey = "showCodexResetForecast"
    static let petPositionLockedKey = "petPositionLocked"
    static let passesPointerInputThroughKey = "passesPointerInputThrough"
    static let selectedCompanionIDKey = "selectedCompanionID"
    static let absorptionCategoryWeightsKey = "absorptionCategoryWeights"
    static let petPanelFrameName = "CodexQuotaPetLockedFrame"
}
